### ISSUE TITLE
Admin page v2

### ISSUE THREAD

**Issue by bracesproul** [bracesproul/lots-o-slots#110]
- [x] New data table
- [x] Split up into separate pages /payments /accounts /users /settings
- [x] Add new accounts display card
- [x] Add account form
- [x] hookup add account form
- [ ] Update default payment account (card that shows PayPal, zelle, cashapp etc with a drop-down to select for each one)
- [x] Add account form (checkbox for admin)
- [x] Edit account info (select on table have open form)
- [x] Delete account button (on table)
- [x] #120
- [x] #121
- [x] #122
- [x] #123
- [ ] withdrawals page, show withdrawal requests, confirmed or unconfirmed
- [ ]
