### ISSUE TITLE
Supabase auth integration (tracking)

### ISSUE THREAD

**Issue by bracesproul** [bracesproul/lots-o-slots#83]
- [x] Add supabase auth inside `./services/supabase/auth`
- [x] Add login, signup, and delete account methods
- [x] Add `/logout` route
- [x] Hookup `/logout` route
- [x] Add `/signup` route
- [x] Hookup `/signup` route
- [x] Add `/login` route
- [x] Hookup `/login` route
- [x] Fix `withAuthRequired` to work with supabase auth
