### ISSUE TITLE
User dashboard page (tracking)

### ISSUE THREAD

**Issue by bracesproul** [bracesproul/lots-o-slots#85]
- [x] add user info card
- [x] hookup user info card
- [x] add logout button
- [ ] ~~add delete account button~~
- [x] add `Save` button that detects when updates have been made
- [x] hookup `Save` updates button
