### ISSUE TITLE
Bitcoin API v1

### ISSUE THREAD

**Issue by bracesproul** [bracesproul/lots-o-slots#96]
- [ ] #97 
- [ ] #98
- [ ] Add discord alerts on all new transactions
- [ ] Add crypto addresses entity
- [ ] Add script to insert crypto addresses production 
- [ ] Add job to request txn data
- [ ] Run scripts in production (brace)
